api:
    resource: '.'
    type: 'api_platform'

app:
    resource: '@AppBundle/Action/'
    type: 'annotation'

user_special:
    path: '/users/{id}/best'
    methods:  ['GET']
    defaults:
        _controller: 'AppBundle:User:best'
        _api_resource_class: 'AppBundle\Entity\User'
        _api_item_operation_name: 'best'

users_best:
    path: '/users/best'
    methods:  ['GET']
    defaults:
        _controller: 'AppBundle:User:best'
        _api_resource_class: 'AppBundle\Entity\User'
        _api_item_operation_name: 'best'